server:
  port: 9001

spring:
  application:
    name: tickethub-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tickethub_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: wjdekdms0814
  sql:
    init:
      mode: always

  jpa:
    database:
    open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  jwt:
    secret: lakufhwkuhfkjsdfhu2387yr73hr13o873878y374y1wlkugwkehsggiqlei8374679kuhwuefjswhehbneklcoufyyey38r949TERGTTAFSfskfgwelskjfgsfaghsullau2837ryhsd